Repository JasperFx/weasel, pull requests merged in 2021-11, with the labels that each got.

#37 Add support for custom index methods and arbitrary index storage parameters
  src/Weasel.Postgresql.Tests/Tables/IndexDefinitionTests.cs
  src/Weasel.Postgresql/Tables/IndexDefinition.cs
  src/Weasel.Postgresql/Tables/IndexMethod.cs
Labels: enhancement, indexing

#49 Handle PrimaryKeyName longer than Postgres's default NAMEDATALEN limit
  src/Weasel.Postgresql.Tests/Tables/detecting_table_deltas.cs
  src/Weasel.Postgresql/Tables/Table.FetchExisting.cs
  src/Weasel.Postgresql/Tables/Table.cs
  src/Weasel.Postgresql/Tables/TableDelta.cs
Labels: bug

#50 Update index definition to handle INCLUDE clause
  src/Weasel.Postgresql.Tests/Tables/IndexDefinitionTests.cs
  src/Weasel.Postgresql/Tables/IndexDefinition.cs
Labels: bug

#51 Fix index definition parse logic to handle tablespace
  src/Weasel.Postgresql.Tests/Tables/IndexDefinitionTests.cs
  src/Weasel.Postgresql/Tables/IndexDefinition.cs
Labels: bug, indexing
